export const players = [
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    achievement1: {
      image: "../../predator.png",
      text: "GRINDER",
    },
    achievement2: {
      image: "../../master.png",
      text: "Ranked Good",
    },
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
  },
];
