export const teamPerformances = [
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
  {
    teamPerformanceId: "lakjhsflkajshf",
    name: "team1",
    killsTotal: 12,
    placement: 5,
    matchId: "akjdhflkjahf",
    playerPerformances: [
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 13,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
      {
        playerPerformanceId: "asdhfaljsdfhlkajsdhf",
        playerId: "akjdhflakjhf",
        Player: {
          id: "lakjsbflkjasflkjadsbf",
          image: "../../wraith.png",
          name: "byxir",
          clubName: "Taras&Stas",
          mainCharacter: 5,
          pts: 387,
        },
        kills: 4,
        ptsDelta: 12,
        characterPlayed: 5,
      },
    ],
  },
];
