export const players = [
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Brazzers",
    mainCharacter: 19,
    pts: 387,
    badges: [
      { image: "../../master.png", text: "Ranked Good" },
      { image: "../../predator.png", text: "GRINDER" },
    ],
  },
  {
    id: "fhdnfgb",
    image: "../../wraith.png",
    name: "malahit.",
    clubName: "Камчатские айсберги",
    mainCharacter: 9,
    pts: 4732,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lkajgjks",
    image: "../../wraith.png",
    name: "Дамский Угодник217",
    clubName: "Brazzers",
    mainCharacter: 11,
    pts: 483,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "erjfhlakjdsfh",
    image: "../../wraith.png",
    name: "kust'",
    clubName: "Brazzers",
    mainCharacter: 3,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "Rafs0BiL1Sh",
    clubName: "Brazzers",
    mainCharacter: 10,
    pts: 335,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "slkjfghljkfhgl",
    image: "../../wraith.png",
    name: "drronflaer",
    clubName: "днище",
    mainCharacter: 1,
    pts: 111,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lkajhfljkashdfljfh",
    image: "../../wraith.png",
    name: "9uamolly",
    clubName: "CIRK",
    mainCharacter: 3,
    pts: 337,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "reiuytudg8gzcbvczbzbjhfg",
    image: "../../wraith.png",
    name: "Nine",
    clubName: "NXBL",
    mainCharacter: 2,
    pts: 3873,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "aksdfgdsfgdfglfshgsdfbdfsb",
    image: "../../wraith.png",
    name: "krEy",
    clubName: "NXBL",
    mainCharacter: 3,
    pts: 3871,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "aklsjhfldfgfghfghakjsfh",
    image: "../../wraith.png",
    name: "requ1em",
    clubName: "днище",
    mainCharacter: 2,
    pts: 32,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjszsdvsdfsdfbflkjasflkjadsbfakljhdfljahs",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflkjbxcvbcbasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "djdthtrhrthtrh",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflvxcxvxkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflkjfxgngfxngasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsfwezfewfsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflkjasflkjzxcvzesadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "lakjsbflkcvxcvzxvjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "fyuklfiukfghj",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "aseraweraf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "dghmdgndg",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "avdavfva",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "234523454",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "dfhffbfgb",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    id: "asdfadfsf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainCharacter: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
];
