export const scrims = [
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 1,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 1,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 1,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 1,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 0,
  },
  {
    id: "eglasjhdfl",
    image: "../../aplogowhite.jpg",
    title: "AP Ranked Scrim",
    description: "AP regular ranked scrim",
    date: "2017-01-26",
    averageRank: 591,
    category: 1,
  },
];
