export const clubs = [
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/be/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3_%D0%B2_%D0%90%D0%BD%D1%82%D0%B0%D1%80%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B9_%D0%BF%D1%80%D0%BE%D0%BB%D0%B8%D0%B2%D0%B5.jpg",
    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
  {
    id: "alsfgliuashfliuahsf",
    name: "Камчатские Айсберги",
    image:
      "https://static.wikia.nocookie.net/navigator/images/9/9d/%D0%90%D0%B9%D1%81%D0%B1%D0%B5%D1%80%D0%B3.jpg/revision/latest/scale-to-width-down/849?cb=20130902164958&path-prefix=ru",

    members: [
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
        achievement1: {
          image: "../../predator.png",
          text: "GRINDER",
        },
        achievement2: {
          image: "../../master.png",
          text: "Ranked Good",
        },
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
      {
        id: "lakjsbflkjasflkjadsbf",
        image: "../../wraith.png",
        name: "byxir",
        clubName: "Taras&Stas",
        mainCharacter: 5,
        pts: 387,
      },
    ],
  },
];
