export const members = [
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 1,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
  {
    id: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    pts: 387,
    role: 0,
  },
];
