export const players = [
  {
    playerId: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Brazzers",
    mainLegend: 19,
    pts: 387,
    badges: [
      { image: "../../master.png", text: "Ranked Good" },
      { image: "../../predator.png", text: "GRINDER" },
    ],
  },
  {
    playerId: "fhdnfgb",
    image: "../../wraith.png",
    name: "malahit.",
    clubName: "Камчатские айсберги",
    mainLegend: 9,
    pts: 4732,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lkajgjks",
    image: "../../wraith.png",
    name: "Дамский Угодник217",
    clubName: "Brazzers",
    mainLegend: 11,
    pts: 483,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "erjfhlakjdsfh",
    image: "../../wraith.png",
    name: "kust'",
    clubName: "Brazzers",
    mainLegend: 3,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "Rafs0BiL1Sh",
    clubName: "Brazzers",
    mainLegend: 10,
    pts: 335,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "slkjfghljkfhgl",
    image: "../../wraith.png",
    name: "drronflaer",
    clubName: "днище",
    mainLegend: 1,
    pts: 111,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lkajhfljkashdfljfh",
    image: "../../wraith.png",
    name: "9uamolly",
    clubName: "CIRK",
    mainLegend: 3,
    pts: 337,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "reiuytudg8gzcbvczbzbjhfg",
    image: "../../wraith.png",
    name: "Nine",
    clubName: "NXBL",
    mainLegend: 2,
    pts: 3873,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "aksdfgdsfgdfglfshgsdfbdfsb",
    image: "../../wraith.png",
    name: "krEy",
    clubName: "NXBL",
    mainLegend: 3,
    pts: 3871,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "aklsjhfldfgfghfghakjsfh",
    image: "../../wraith.png",
    name: "requ1em",
    clubName: "днище",
    mainLegend: 2,
    pts: 32,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjszsdvsdfsdfbflkjasflkjadsbfakljhdfljahs",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflkjbxcvbcbasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "djdthtrhrthtrh",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflvxcxvxkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflkjfxgngfxngasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsfwezfewfsbflkjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflkjasflkjzxcvzesadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "lakjsbflkcvxcvzxvjasflkjadsbf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "fyuklfiukfghj",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "aseraweraf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "dghmdgndg",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "avdavfva",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "234523454",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "dfhffbfgb",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
  {
    playerId: "asdfadfsf",
    image: "../../wraith.png",
    name: "byxir",
    clubName: "Taras&Stas",
    mainLegend: 5,
    pts: 387,
    badges: [
      { image: "../../predator.png", text: "PRED ARENAS" },
      { image: "../../master.png", text: "Уважаемый Человек" },
    ],
  },
];
